hello:
	curl http://localhost:8080

demo:
	curl http://localhost:8080/static/demo.json

users:
	curl http://localhost:8080/static/users.json

user:
	curl http://localhost:8080/user/1
	@echo
	curl http://localhost:8080/user/2
	@echo
	curl http://localhost:8080/user/3
	@echo
	curl http://localhost:8080/user/4

