[package]
name = "test_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yx_common   = { version = "0.1.0", path = "../common" }
