.PHONY: start startd stop login

# 前台启动
start:
	cd ../test_mysql && make start

# 后台启动
startd:
	cd ../test_mysql && make startd

# 停止后台
stop:
	cd ../test_mysql && make stop

# shell 访问
login:
	cd ../test_mysql && make login
